version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    # volumes:
    #   - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user # Optional: Set root username
      MONGO_INITDB_ROOT_PASSWORD: root_password # Optional: Set root password
